source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.1'
gem 'sprockets', '~> 2.12.3'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'

gem 'slim-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'spring'
  gem 'yaml_db'
end

# Users
#gem 'devise'

# file upload
#gem 'paperclip'

# Admin
#gem 'rails_admin'
